# Generated by Django 5.0 on 2024-01-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lawyer_adresse_lawyer_description_lawyer_langues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_images/'),
        ),
    ]
