# Generated by Django 5.0 on 2024-01-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lawyer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../../frontend/src/component/lawyer_images/'),
        ),
    ]
