# Generated by Django 5.0 on 2024-01-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lawyer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./lawyer_images/'),
        ),
    ]
